paths:
  /api/products:
    get:
      tags: 
        - Products
      summary: Get all products
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                {
                  status: success,
                  "payload": [
                    {
                      "_id": "6513a2268803bccd46fbd698",
                      "title": "Auriculares Inalámbricos Bluetooth",
                      "description": "Auriculares inalámbricos Bluetooth con cancelación de ruido para una experiencia de audio inmersiva.",
                      "price": 79.99,
                      "status": true,
                      "thumbnail": [
                        
                      ],
                      "code": "P010",
                      "stock": 10,
                      "category": "Electrónica",
                      "owner": "admin",
                      "id": "6513a2268803bccd46fbd698"
                    },
                    {
                      "_id": "6513a2268803bccd46fbd696",
                      "title": "Pantalones de Mezclilla Modernos",
                      "description": "Pantalones de mezclilla modernos y cómodos para hombres y mujeres.",
                      "price": 49.99,
                      "status": true,
                      "thumbnail": [
                        
                      ],
                      "code": "P008",
                      "stock": 38,
                      "category": "Ropa",
                      "owner": "admin",
                      "id": "6513a2268803bccd46fbd696"
                    },
                    {
                      "_id": "6513a2268803bccd46fbd69d",
                      "title": "Set de Ollas y Sartenes Antiadherentes",
                      "description": "Set de ollas y sartenes antiadherentes de alta calidad para cocinar sin problemas.",
                      "price": 129.99,
                      "status": true,
                      "thumbnail": [
                        
                      ],
                      "code": "P015",
                      "stock": 34,
                      "category": "Hogar",
                      "owner": "admin",
                      "id": "6513a2268803bccd46fbd69d"
                    },
                    {
                      "_id": "6513a2268803bccd46fbd69b",
                      "title": "Cámara DSLR Profesional",
                      "description": "Cámara DSLR profesional con lentes intercambiables para capturar momentos inolvidables.",
                      "price": 699.99,
                      "status": true,
                      "thumbnail": [
                        
                      ],
                      "code": "P013",
                      "stock": 21,
                      "category": "Electrónica",
                      "owner": "admin",
                      "id": "6513a2268803bccd46fbd69b"
                    },
                    {
                      "_id": "6513a2268803bccd46fbd694",
                      "title": "Juego de Sábanas de Lujo",
                      "description": "Juego de sábanas de lujo de algodón suave para un confort excepcional.",
                      "price": 69.99,
                      "status": true,
                      "thumbnail": [
                        
                      ],
                      "code": "P006",
                      "stock": 69,
                      "category": "Hogar",
                      "owner": "admin",
                      "id": "6513a2268803bccd46fbd694"
                    }
                  ]
                  }
        "500":
          description: Internal Server Error
          content:
            application/json:
              example:
                status: error
                error: server problem here

    post:
      tags: 
        - Products
      security:
        - bearerAuth: []
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            example:
              "payload": {
                "title": "new product title",
                "description": "new product description",
                "price": 79.99,
                "status": true,
                "thumbnail": [
                          
                        ],
                "code": "SADSA4583666",
                "stock": 40,
                "category": "new product category",
              }
                           
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              example: 
                {
                status: "success",              
                payload: {
                  "_id":"6513a2268803bccd46fbd698",
                  "title":"new product title",
                  "description": "new product description",
                  "price": 79.99,
                  "stock": 40,
                  "category": "new product category",
                  "owner": "admin",
                  }
                  }
        "500": 
          description: failled operation
          content:
            application/json:
              example:
                status: error
                error: internal server error

  /api/products/{pid}:
    get:
      tags: 
        - Products
      summary: Get a product by ID
      parameters:
        - name: productId
          in: path
          required: true
          description: ID of the product
          example: "6513a2268803bccd46fbd69d"
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                {
                status: success,
                payload: {
                  "_id": "6513a2268803bccd46fbd69d",
                  "title": "Set de Ollas y Sartenes Antiadherentes",
                  "description": "Set de ollas y sartenes antiadherentes de alta calidad para cocinar sin problemas.",
                  "price": 129.99,
                  "status": true,
                  "thumbnail": [],
                  "code": "P015",
                  "stock": 34,
                  "category": "Hogar",
                  "owner": "admin"                
                }
                }
        '400':
          description: product does not found
          content:
            application/json:
              example:
                {
                status: "error",
                error: "product does not found"
                }
    put:
      tags: 
        - Products
      summary: Update a product by ID
      parameters:
        - name: productId
          in: path
          required: true
          description: ID of the product
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties:
                title:
                  type: string
                  required: true
                category:
                  type: string
                  required: true
                size:
                  type: string
                code:
                  type: string
                description:
                  type: string
                price:
                  type: number
                  required: true
                stock:
                  type: number
                  required: true
                thumbnail:
                  type: string
                status:
                  type: boolean
              required:
                - title
                - category
                - price
                - stock
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    delete:
      tags: 
        - Products
      summary: Delete a product by ID
      parameters:
        - name: productId
          in: path
          required: true
          description: ID of the product
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

components:
  schemas:
    Product:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        price:
          type: number
        status:
          type: boolean
          description: if stock = 0 status = false
        thumbnail:
          type: string
          description: array with pictures
        code:
          type: string
          description: code generated automatically
        stock:
          type: number
        category:
          type: string
        owner:
          type: string
          description: user who charges the product
          default: admin

      required:
        - title
        - category
        - price
        - stock
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT